import type { MCPToolDefinition } from '../../types';

export const TOOLS: MCPToolDefinition[] = [
  // === Auth (2) ===
  { name: 'gws_auth_clear', description: 'Clears the authentication credentials, forcing a re-login on the next request.', inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'gws_auth_refreshToken', description: 'Manually triggers the token refresh process.', inputSchema: { type: 'object', properties: {}, required: [] } },

  // === Docs (8) ===
  { name: 'gws_docs_create', description: 'Creates a new Google Doc. Can be blank or with Markdown content.', inputSchema: { type: 'object', properties: { title: { type: 'string', description: 'The title for the new Google Doc.' }, folderName: { type: 'string', description: 'The name of the folder to create the document in.' }, markdown: { type: 'string', description: 'The Markdown content to create the document from.' } }, required: ['title'] } },
  { name: 'gws_docs_insertText', description: 'Inserts text at the beginning of a Google Doc.', inputSchema: { type: 'object', properties: { documentId: { type: 'string', description: 'The ID of the document to modify.' }, text: { type: 'string', description: 'The text to insert at the beginning of the document.' }, tabId: { type: 'string', description: 'The ID of the tab to modify.' } }, required: ['documentId', 'text'] } },
  { name: 'gws_docs_find', description: 'Finds Google Docs by searching for a query in their title. Supports pagination.', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'The text to search for in the document titles.' }, pageToken: { type: 'string', description: 'The token for the next page of results.' }, pageSize: { type: 'number', description: 'The maximum number of results to return.' } }, required: ['query'] } },
  { name: 'gws_docs_move', description: 'Moves a document to a specified folder.', inputSchema: { type: 'object', properties: { documentId: { type: 'string', description: 'The ID of the document to move.' }, folderName: { type: 'string', description: 'The name of the destination folder.' } }, required: ['documentId', 'folderName'] } },
  { name: 'gws_docs_getText', description: 'Retrieves the text content of a Google Doc.', inputSchema: { type: 'object', properties: { documentId: { type: 'string', description: 'The ID of the document to read.' }, tabId: { type: 'string', description: 'The ID of the tab to read.' } }, required: ['documentId'] } },
  { name: 'gws_docs_appendText', description: 'Appends text to the end of a Google Doc.', inputSchema: { type: 'object', properties: { documentId: { type: 'string', description: 'The ID of the document to modify.' }, text: { type: 'string', description: 'The text to append to the document.' }, tabId: { type: 'string', description: 'The ID of the tab to modify.' } }, required: ['documentId', 'text'] } },
  { name: 'gws_docs_replaceText', description: 'Replaces all occurrences of a given text with new text in a Google Doc.', inputSchema: { type: 'object', properties: { documentId: { type: 'string', description: 'The ID of the document to modify.' }, findText: { type: 'string', description: 'The text to find in the document.' }, replaceText: { type: 'string', description: 'The text to replace the found text with.' }, tabId: { type: 'string', description: 'The ID of the tab to modify.' } }, required: ['documentId', 'findText', 'replaceText'] } },
  { name: 'gws_docs_extractIdFromUrl', description: 'Extracts the document ID from a Google Workspace URL.', inputSchema: { type: 'object', properties: { url: { type: 'string', description: 'The URL of the Google Workspace document.' } }, required: ['url'] } },

  // === Drive (4) ===
  { name: 'gws_drive_findFolder', description: 'Finds a folder by name in Google Drive.', inputSchema: { type: 'object', properties: { folderName: { type: 'string', description: 'The name of the folder to find.' } }, required: ['folderName'] } },
  { name: 'gws_drive_createFolder', description: 'Creates a new folder in Google Drive.', inputSchema: { type: 'object', properties: { name: { type: 'string', description: 'The name of the new folder.' }, parentId: { type: 'string', description: 'The ID of the parent folder.' } }, required: ['name'] } },
  { name: 'gws_drive_search', description: 'Searches for files and folders in Google Drive.', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'A search term, Google Drive URL, or full query string.' }, pageSize: { type: 'number', description: 'The maximum number of results to return.' }, pageToken: { type: 'string', description: 'The token for the next page of results.' }, corpus: { type: 'string', description: 'The corpus of files to search (e.g., "user", "domain").' }, unreadOnly: { type: 'boolean', description: 'Whether to filter for unread files only.' }, sharedWithMe: { type: 'boolean', description: 'Whether to search for files shared with the user.' } }, required: [] } },
  { name: 'gws_drive_downloadFile', description: 'Downloads the content of a file from Google Drive to a local path.', inputSchema: { type: 'object', properties: { fileId: { type: 'string', description: 'The ID of the file to download.' }, localPath: { type: 'string', description: 'The local file path where the content should be saved.' } }, required: ['fileId', 'localPath'] } },

  // === Slides (5) ===
  { name: 'gws_slides_getText', description: 'Retrieves the text content of a Google Slides presentation.', inputSchema: { type: 'object', properties: { presentationId: { type: 'string', description: 'The ID or URL of the presentation to read.' } }, required: ['presentationId'] } },
  { name: 'gws_slides_find', description: 'Finds Google Slides presentations by searching for a query. Supports pagination.', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'The text to search for in presentations.' }, pageToken: { type: 'string', description: 'The token for the next page of results.' }, pageSize: { type: 'number', description: 'The maximum number of results to return.' } }, required: ['query'] } },
  { name: 'gws_slides_getMetadata', description: 'Gets metadata about a Google Slides presentation.', inputSchema: { type: 'object', properties: { presentationId: { type: 'string', description: 'The ID or URL of the presentation.' } }, required: ['presentationId'] } },
  { name: 'gws_slides_getImages', description: 'Downloads all images embedded in a Google Slides presentation to a local directory.', inputSchema: { type: 'object', properties: { presentationId: { type: 'string', description: 'The ID or URL of the presentation.' }, localPath: { type: 'string', description: 'The absolute local directory path to download the images to.' } }, required: ['presentationId', 'localPath'] } },
  { name: 'gws_slides_getSlideThumbnail', description: 'Downloads a thumbnail image for a specific slide.', inputSchema: { type: 'object', properties: { presentationId: { type: 'string', description: 'The ID or URL of the presentation.' }, slideObjectId: { type: 'string', description: 'The object ID of the slide.' }, localPath: { type: 'string', description: 'The absolute local file path to download the thumbnail to.' } }, required: ['presentationId', 'slideObjectId', 'localPath'] } },

  // === Sheets (4) ===
  { name: 'gws_sheets_getText', description: 'Retrieves the content of a Google Sheets spreadsheet.', inputSchema: { type: 'object', properties: { spreadsheetId: { type: 'string', description: 'The ID or URL of the spreadsheet to read.' }, format: { type: 'string', enum: ['text', 'csv', 'json'], description: 'Output format (default: text).' } }, required: ['spreadsheetId'] } },
  { name: 'gws_sheets_getRange', description: 'Gets values from a specific range in a Google Sheets spreadsheet.', inputSchema: { type: 'object', properties: { spreadsheetId: { type: 'string', description: 'The ID or URL of the spreadsheet.' }, range: { type: 'string', description: 'The A1 notation range to get (e.g., "Sheet1!A1:B10").' } }, required: ['spreadsheetId', 'range'] } },
  { name: 'gws_sheets_find', description: 'Finds Google Sheets spreadsheets by searching for a query. Supports pagination.', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'The text to search for in spreadsheets.' }, pageToken: { type: 'string', description: 'The token for the next page of results.' }, pageSize: { type: 'number', description: 'The maximum number of results to return.' } }, required: ['query'] } },
  { name: 'gws_sheets_getMetadata', description: 'Gets metadata about a Google Sheets spreadsheet.', inputSchema: { type: 'object', properties: { spreadsheetId: { type: 'string', description: 'The ID or URL of the spreadsheet.' } }, required: ['spreadsheetId'] } },

  // === Calendar (7) ===
  { name: 'gws_calendar_list', description: "Lists all of the user's calendars.", inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'gws_calendar_createEvent', description: 'Creates a new event in a calendar.', inputSchema: { type: 'object', properties: { calendarId: { type: 'string', description: 'The ID of the calendar.' }, summary: { type: 'string', description: 'The summary or title of the event.' }, description: { type: 'string', description: 'The description of the event.' }, start: { type: 'object', properties: { dateTime: { type: 'string', description: 'Start time in ISO 8601 format.' } }, required: ['dateTime'] }, end: { type: 'object', properties: { dateTime: { type: 'string', description: 'End time in ISO 8601 format.' } }, required: ['dateTime'] }, attendees: { type: 'array', items: { type: 'string' }, description: 'Email addresses of attendees.' } }, required: ['calendarId', 'summary', 'start', 'end'] } },
  { name: 'gws_calendar_listEvents', description: 'Lists events from a calendar. Defaults to upcoming events.', inputSchema: { type: 'object', properties: { calendarId: { type: 'string', description: 'The ID of the calendar.' }, timeMin: { type: 'string', description: 'The start time for the event search.' }, timeMax: { type: 'string', description: 'The end time for the event search.' }, attendeeResponseStatus: { type: 'array', items: { type: 'string' }, description: 'The response status of the attendee.' } }, required: ['calendarId'] } },
  { name: 'gws_calendar_getEvent', description: 'Gets the details of a specific calendar event.', inputSchema: { type: 'object', properties: { eventId: { type: 'string', description: 'The ID of the event.' }, calendarId: { type: 'string', description: 'The ID of the calendar.' } }, required: ['eventId'] } },
  { name: 'gws_calendar_findFreeTime', description: 'Finds a free time slot for multiple people to meet.', inputSchema: { type: 'object', properties: { attendees: { type: 'array', items: { type: 'string' }, description: 'Email addresses of attendees.' }, timeMin: { type: 'string', description: 'Start time in ISO 8601 format.' }, timeMax: { type: 'string', description: 'End time in ISO 8601 format.' }, duration: { type: 'number', description: 'Duration of the meeting in minutes.' } }, required: ['attendees', 'timeMin', 'timeMax', 'duration'] } },
  { name: 'gws_calendar_updateEvent', description: 'Updates an existing event in a calendar.', inputSchema: { type: 'object', properties: { eventId: { type: 'string', description: 'The ID of the event.' }, calendarId: { type: 'string', description: 'The ID of the calendar.' }, summary: { type: 'string', description: 'New summary.' }, description: { type: 'string', description: 'New description.' }, start: { type: 'object', properties: { dateTime: { type: 'string' } } }, end: { type: 'object', properties: { dateTime: { type: 'string' } } }, attendees: { type: 'array', items: { type: 'string' } } }, required: ['eventId'] } },
  { name: 'gws_calendar_respondToEvent', description: 'Responds to a meeting invitation (accept, decline, or tentative).', inputSchema: { type: 'object', properties: { eventId: { type: 'string', description: 'The ID of the event.' }, calendarId: { type: 'string', description: 'The ID of the calendar.' }, responseStatus: { type: 'string', enum: ['accepted', 'declined', 'tentative'], description: 'Your response.' }, sendNotification: { type: 'boolean', description: 'Whether to send a notification.' }, responseMessage: { type: 'string', description: 'Optional message.' } }, required: ['eventId', 'responseStatus'] } },
  { name: 'gws_calendar_deleteEvent', description: 'Deletes an event from a calendar.', inputSchema: { type: 'object', properties: { eventId: { type: 'string', description: 'The ID of the event.' }, calendarId: { type: 'string', description: 'The ID of the calendar.' } }, required: ['eventId'] } },

  // === Chat (8) ===
  { name: 'gws_chat_listSpaces', description: 'Lists the spaces the user is a member of.', inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'gws_chat_findSpaceByName', description: 'Finds a Google Chat space by its display name.', inputSchema: { type: 'object', properties: { displayName: { type: 'string', description: 'The display name of the space to find.' } }, required: ['displayName'] } },
  { name: 'gws_chat_sendMessage', description: 'Sends a message to a Google Chat space.', inputSchema: { type: 'object', properties: { spaceName: { type: 'string', description: 'The name of the space (e.g., spaces/AAAAN2J52O8).' }, message: { type: 'string', description: 'The message to send.' }, threadName: { type: 'string', description: 'The resource name of the thread to reply to.' } }, required: ['spaceName', 'message'] } },
  { name: 'gws_chat_getMessages', description: 'Gets messages from a Google Chat space.', inputSchema: { type: 'object', properties: { spaceName: { type: 'string', description: 'The name of the space.' }, threadName: { type: 'string', description: 'Thread to filter by.' }, unreadOnly: { type: 'boolean', description: 'Return only unread messages.' }, pageSize: { type: 'number', description: 'Max messages to return.' }, pageToken: { type: 'string', description: 'Next page token.' }, orderBy: { type: 'string', description: 'Order (e.g., "createTime desc").' } }, required: ['spaceName'] } },
  { name: 'gws_chat_sendDm', description: 'Sends a direct message to a user.', inputSchema: { type: 'object', properties: { email: { type: 'string', description: 'Email address of the recipient.' }, message: { type: 'string', description: 'The message to send.' }, threadName: { type: 'string', description: 'Thread to reply to.' } }, required: ['email', 'message'] } },
  { name: 'gws_chat_findDmByEmail', description: "Finds a Google Chat DM space by a user's email address.", inputSchema: { type: 'object', properties: { email: { type: 'string', description: 'Email address of the user.' } }, required: ['email'] } },
  { name: 'gws_chat_listThreads', description: 'Lists threads from a Google Chat space in reverse chronological order.', inputSchema: { type: 'object', properties: { spaceName: { type: 'string', description: 'The name of the space.' }, pageSize: { type: 'number', description: 'Max threads to return.' }, pageToken: { type: 'string', description: 'Next page token.' } }, required: ['spaceName'] } },
  { name: 'gws_chat_setUpSpace', description: 'Sets up a new Google Chat space with a display name and members.', inputSchema: { type: 'object', properties: { displayName: { type: 'string', description: 'The display name of the space.' }, userNames: { type: 'array', items: { type: 'string' }, description: 'User names to add (e.g., users/12345678).' } }, required: ['displayName', 'userNames'] } },

  // === Gmail (9) ===
  { name: 'gws_gmail_search', description: 'Search for emails in Gmail using query parameters.', inputSchema: { type: 'object', properties: { query: { type: 'string', description: 'Search query (same as Gmail search box).' }, maxResults: { type: 'number', description: 'Maximum results to return.' }, pageToken: { type: 'string', description: 'Next page token.' }, labelIds: { type: 'array', items: { type: 'string' }, description: 'Filter by label IDs.' }, includeSpamTrash: { type: 'boolean', description: 'Include SPAM and TRASH.' } }, required: [] } },
  { name: 'gws_gmail_get', description: 'Get the full content of a specific email message.', inputSchema: { type: 'object', properties: { messageId: { type: 'string', description: 'The ID of the message.' }, format: { type: 'string', enum: ['minimal', 'full', 'raw', 'metadata'], description: 'Format of the message.' } }, required: ['messageId'] } },
  { name: 'gws_gmail_downloadAttachment', description: 'Downloads an attachment from a Gmail message to a local file.', inputSchema: { type: 'object', properties: { messageId: { type: 'string', description: 'The ID of the message.' }, attachmentId: { type: 'string', description: 'The ID of the attachment.' }, localPath: { type: 'string', description: 'Local path to save the attachment.' } }, required: ['messageId', 'attachmentId', 'localPath'] } },
  { name: 'gws_gmail_modify', description: 'Modify a Gmail message labels. System labels: INBOX, SPAM, TRASH, UNREAD, STARRED, IMPORTANT.', inputSchema: { type: 'object', properties: { messageId: { type: 'string', description: 'The ID of the message.' }, addLabelIds: { type: 'array', items: { type: 'string' }, description: 'Label IDs to add.' }, removeLabelIds: { type: 'array', items: { type: 'string' }, description: 'Label IDs to remove.' } }, required: ['messageId'] } },
  { name: 'gws_gmail_send', description: 'Send an email message.', inputSchema: { type: 'object', properties: { to: { type: 'string', description: 'Recipient email address(es).' }, subject: { type: 'string', description: 'Email subject.' }, body: { type: 'string', description: 'Email body content.' }, cc: { type: 'string', description: 'CC recipients.' }, bcc: { type: 'string', description: 'BCC recipients.' }, isHtml: { type: 'boolean', description: 'Whether body is HTML.' } }, required: ['to', 'subject', 'body'] } },
  { name: 'gws_gmail_createDraft', description: 'Create a draft email message.', inputSchema: { type: 'object', properties: { to: { type: 'string', description: 'Recipient email address(es).' }, subject: { type: 'string', description: 'Email subject.' }, body: { type: 'string', description: 'Email body content.' }, cc: { type: 'string', description: 'CC recipients.' }, bcc: { type: 'string', description: 'BCC recipients.' }, isHtml: { type: 'boolean', description: 'Whether body is HTML.' } }, required: ['to', 'subject', 'body'] } },
  { name: 'gws_gmail_sendDraft', description: 'Send a previously created draft email.', inputSchema: { type: 'object', properties: { draftId: { type: 'string', description: 'The ID of the draft to send.' } }, required: ['draftId'] } },
  { name: 'gws_gmail_listLabels', description: "List all Gmail labels in the user's mailbox.", inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'gws_gmail_createLabel', description: 'Create a new Gmail label.', inputSchema: { type: 'object', properties: { name: { type: 'string', description: 'The display name of the label.' }, labelListVisibility: { type: 'string', enum: ['labelShow', 'labelHide', 'labelShowIfUnread'], description: 'Visibility in label list.' }, messageListVisibility: { type: 'string', enum: ['show', 'hide'], description: 'Visibility in message list.' } }, required: ['name'] } },

  // === Time (3) ===
  { name: 'gws_time_getCurrentDate', description: 'Gets the current date in both UTC and local time.', inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'gws_time_getCurrentTime', description: 'Gets the current time in both UTC and local time.', inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'gws_time_getTimeZone', description: 'Gets the local timezone.', inputSchema: { type: 'object', properties: {}, required: [] } },

  // === People (3) ===
  { name: 'gws_people_getUserProfile', description: "Gets a user's profile information.", inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'The ID of the user.' }, email: { type: 'string', description: 'The email address of the user.' }, name: { type: 'string', description: 'The name of the user.' } }, required: [] } },
  { name: 'gws_people_getMe', description: 'Gets the profile information of the authenticated user.', inputSchema: { type: 'object', properties: {}, required: [] } },
  { name: 'gws_people_getUserRelations', description: "Gets a user's relations (manager, spouse, assistant, etc.).", inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'The ID of the user.' }, relationType: { type: 'string', description: 'Filter by relation type (e.g., "manager", "spouse").' } }, required: [] } },
];
